version: '3'
services:
    redis:
        container_name: redis_cache
        image: redis:3.2.12
        volumes:
            - ./redis:/data
    mysql:
        container_name: mysql_db
        image: mysql:5.6
        environment: 
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql
            restart: always
    app:
        build: .
        container_name: py_app
        volumes: :
            - ./app:/opt/app
        command: python /opt/app/main.py
    nginx:
        container_name: nginx_server
        ports:
            - "8080:8080" # "local:containers"
        volumes:
            - ./nginx/lb.conf:/etc/nginx/conf.d/lb.conf
        depends_on:
            - app
 